In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("movement_data.csv")
pd.set_option('display.max_columns', None)
df.head()

,frame,video,x_0,y_0,z_0,visibility_0,x_1,y_1,z_1,visibility_1,x_2,y_2,z_2,visibility_2,x_3,y_3,z_3,visibility_3,x_4,y_4,z_4,visibility_4,x_5,y_5,z_5,visibility_5,x_6,y_6,z_6,visibility_6,x_7,y_7,z_7,visibility_7,x_8,y_8,z_8,visibility_8,x_9,y_9,z_9,visibility_9,x_10,y_10,z_10,visibility_10,x_11,y_11,z_11,visibility_11,x_12,y_12,z_12,visibility_12,x_13,y_13,z_13,visibility_13,x_14,y_14,z_14,visibility_14,x_15,y_15,z_15,visibility_15,x_16,y_16,z_16,visibility_16,x_17,y_17,z_17,visibility_17,x_18,y_18,z_18,visibility_18,x_19,y_19,z_19,visibility_19,x_20,y_20,z_20,visibility_20,x_21,y_21,z_21,visibility_21,x_22,y_22,z_22,visibility_22,x_23,y_23,z_23,visibility_23,x_24,y_24,z_24,visibility_24,x_25,y_25,z_25,visibility_25,x_26,y_26,z_26,visibility_26,x_27,y_27,z_27,visibility_27,x_28,y_28,z_28,visibility_28,x_29,y_29,z_29,visibility_29,x_30,y_30,z_30,visibility_30,x_31,y_31,z_31,visibility_31,x_32,y_32,z_32,visibility_32,action,speed
0,0,caminar_adelante_01_lento.mp4,0.494932,0.381814,-0.429925,0.999991,0.504290,0.372289,-0.405916,0.999961,0.511065,0.372317,-0.405937,0.999963,0.515471,0.372297,-0.405898,0.999958,0.484242,0.372535,-0.406576,0.999961,0.478115,0.372717,-0.406554,0.999957,0.471747,0.373031,-0.406499,0.999949,0.524824,0.375629,-0.224841,0.999928,0.464894,0.377227,-0.230506,0.999904,0.507653,0.391659,-0.358006,0.999976,0.484276,0.391893,-0.359718,0.999974,0.581873,0.430858,-0.108993,0.999978,0.419451,0.429972,-0.084593,0.999953,0.603599,0.498800,-0.045595,0.992029,0.400318,0.499199,-0.006632,0.977627,0.600652,0.562703,-0.214522,0.991126,0.386766,0.558431,-0.154304,0.971676,0.611229,0.583747,-0.268649,0.980273,0.379280,0.580516,-0.202434,0.948384,0.600093,0.582589,-0.327197,0.981502,0.386478,0.579089,-0.260311,0.951286,0.592367,0.575620,-0.241024,0.976459,0.392233,0.572100,-0.180551,0.944375,0.546291,0.564914,-0.015679,0.999559,0.452321,0.565341,0.015819,0.999677,0.550021,0.665568,-0.032618,0.991451,0.439646,0.663711,-0.015438,0.992905,0.546776,0.765985,0.145853,0.989309,0.441383,0.767915,0.163864,0.992875,0.527279,0.783015,0.149020,0.913579,0.454787,0.783954,0.166905,0.918846,0.561891,0.801943,-0.056345,0.983314,0.409677,0.801093,-0.040579,0.985668,caminar_adelante,lento
1,1,caminar_adelante_01_lento.mp4,0.494933,0.380530,-0.430043,0.999991,0.504194,0.371235,-0.405916,0.999961,0.510805,0.371225,-0.405937,0.999962,0.515385,0.371273,-0.405899,0.999958,0.484258,0.371766,-0.406859,0.999961,0.478123,0.372123,-0.406838,0.999956,0.471820,0.372512,-0.406800,0.999949,0.524602,0.375367,-0.224762,0.999927,0.464898,0.377140,-0.232618,0.999904,0.507739,0.390291,-0.358238,0.999976,0.484295,0.390722,-0.360654,0.999974,0.581893,0.430859,-0.103927,0.999977,0.419388,0.430150,-0.095921,0.999953,0.603615,0.498805,-0.040188,0.991120,0.399566,0.499148,-0.018565,0.977394,0.600205,0.562647,-0.214522,0.989888,0.386777,0.558631,-0.161100,0.970526,0.609434,0.583756,-0.268520,0.978203,0.379185,0.580443,-0.208540,0.946613,0.598147,0.582596,-0.327075,0.979576,0.386092,0.579085,-0.268836,0.949635,0.591300,0.575836,-0.241051,0.974058,0.391806,0.572772,-0.188009,0.942419,0.546253,0.565137,-0.004984,0.999564,0.452022,0.565328,0.005102,0.999681,0.550323,0.667119,-0.027915,0.991653,0.441711,0.666957,-0.032789,0.993081,0.546636,0.766402,0.148489,0.989627,0.440633,0.767878,0.149094,0.992932,0.527838,0.782200,0.150975,0.913084,0.454480,0.783723,0.151743,0.915562,0.561687,0.803671,-0.060737,0.983685,0.409467,0.801181,-0.067756,0.985817,caminar_adelante,lento
2,2,caminar_adelante_01_lento.mp4,0.495061,0.379697,-0.367841,0.999991,0.504193,0.370430,-0.340793,0.999960,0.510750,0.370373,-0.340840,0.999962,0.515363,0.370457,-0.340831,0.999957,0.484404,0.371128,-0.343679,0.999960,0.478227,0.371609,-0.343652,0.999956,0.472012,0.372085,-0.343646,0.999949,0.524374,0.375009,-0.160407,0.999926,0.464898,0.377032,-0.174434,0.999905,0.507945,0.389412,-0.297820,0.999976,0.484360,0.389975,-0.301943,0.999974,0.581853,0.430859,-0.052712,0.999976,0.419228,0.430209,-0.056853,0.999952,0.603371,0.498586,-0.024020,0.989551,0.398607,0.499095,0.003387,0.976887,0.597925,0.561271,-0.218735,0.988076,0.386783,0.558744,-0.142992,0.969125,0.604789,0.582960,-0.277080,0.975535,0.379110,0.580426,-0.193694,0.944581,0.593222,0.581611,-0.332784,0.977044,0.385914,0.579086,-0.253664,0.947722,0.587473,0.575126,-0.245594,0.970858,0.391568,0.573133,-0.170151,0.940218,0.546212,0.565534,-0.002919,0.999576,0.451803,0.565446,0.003073,0.999690,0.550911,0.667733,-0.026254,0.991907,0.442584,0.668117,-0.035798,0.993253,0.546635,0.766539,0.149305,0.989936,0.440127,0.767803,0.147073,0.993014,0.528458,0.781430,0.151615,0.911968,0.454281,0.783442,0.149781,0.912877,0.561495,0.804415,-0.062646,0.983990,0.409105,0.801326,-0.068448,0.985955,caminar_adelante,lento
3,3,caminar_adelante_01_lento.mp4,0.495031,0.379111,-0.351790,0.999990,0.504078,0.369870,-0.324738,0.999959,0.510534,0.369804,-0.324789,0.999960,0.515228,0.369909,-0.324788,0.999956,0.484403,0.370683,-0.327524,0.999958,0.478216,0.371275,-0.327490,0.999954,0.472008,0.371820,-0.327495,0.999948,0.524064,0.374754,-0.145550,0.999922,0.464858,0.376952,-0.158857,0.999903,0.507946,0.388890,-0.282273,0.999974,0.484294,0.389524,-0.286197,0.999973,0.581472,0.430858,-0.036293,0.999975,0.419081,0.430212,-0.044922,0.999952,0.602511,0.498475,-0.000050,0.987605,0.397707,0.498824,0.013341,0.976323,0.595665,0.560880,-0.193984,0.985755,0.386718,0.558806,-0.132711,0.967591,0.601777,0.582656,-0.251335,0.972038,0.378807,0.580432,-0.183661,0.942304,0.590455,0.581241,-0.306023,0.973723,0.385628,0.579148,-0.243243,0.945553,0.585113,0.574953,-0.220848,0.966730,0.391163,0.573484,-0.159842,0.937795,0.545642,0.566088,-0.000776,0.999587,0.450939,0.565624,0.000944,0.999698,0.551238,0.668322,-0.022912,0.992162,0.443040,0.668533,-0.036503,0.993419,0.546634,0.766614,0.152215,0.990247,0.439812,0.767699,0.148462,0.993094,0.528746,0.780916,0.154435,0.911204,0.454101,0.783127,0.151387,0.910361,0.561419,0.804844,-0.062371,0.984303,0.409003,0.801392,-0.065578,0.986101,caminar_adelante,lento
4,4,caminar_adelante_01_lento.mp4,0.494595,0.378506,-0.331909,0.999989,0.503511,0.369331,-0.305744,0.999955,0.509930,0.369296,-0.305800,0.999956,0.514862,0.369414,-0.305788,0.999952,0.484134,0.370234,-0.306944,0.999954,0.477926,0.370950,-0.306914,0.999949,0.471735,0.371580,-0.306934,0.999943,0.523715,0.374545,-0.132606,0.999913,0.464756,0.376898,-0.138349,0.999894,0.507875,0.388507,-0.265066,0.999972,0.483859,0.389197,-0.266766,0.999971,0.581150,0.430858,-0.035147,0.999972,0.419016,0.430204,-0.030046,0.999949,0.600988,0.498304,-0.010816,0.985500,0.396968,0.498617,0.013110,0.975045,0.590685,0.560288,-0.219720,0.983597,0.386714,0.558710,-0.138400,0.965463,0.595237,0.582110,-0.280500,0.969114,0.378690,0.580257,-0.193457,0.939558,0.584302,0.580574,-0.332122,0.970896,0.385533,0.579045,-0.250817,0.942920,0.579355,0.574371,-0.245626,0.963134,0.391040,0.573480,-0.165700,0.934905,0.545246,0.566784,-0.001008,0.999593,0.450309,0.566121,0.001167,0.999703,0.551876,0.668428,-0.018771,0.992374,0.443264,0.668651,-0.034349,0.993542,0.546637,0.766607,0.157089,0.990500,0.439643,0.767524,0.151285,0.993127,0.528940,0.779959,0.159476,0.910287,0.453965,0.782675,0.154869,0.908135,0.561253,0.805029,-0.058525,0.984530,0.408855,0.801412,-0.061276,0.986172,caminar_adelante,lento

In [3]:
key_landmarks = {
    'Hombro Izq': 11,
    'Hombro Der': 12,
    'Codo Izq': 13,
    'Codo Der': 14,
    'Cadera Izq': 23,
    'Cadera Der': 24,
    'Rodilla Izq': 25,
    'Rodilla Der': 26,
    'Tobillo Izq': 27,
    'Tobillo Der': 28
}

In [4]:
def extract_landmark_coords(df, idx):
    cols = [f"x_{idx}", f"y_{idx}", f"z_{idx}"]
    return df[cols].to_numpy(dtype=float)

def normalize_landmarks(df, key_landmarks):
    lh = extract_landmark_coords(df, key_landmarks['Cadera Izq'])
    rh = extract_landmark_coords(df, key_landmarks['Cadera Der'])
    la = extract_landmark_coords(df, key_landmarks['Tobillo Izq'])
    ra = extract_landmark_coords(df, key_landmarks['Tobillo Der'])

    hip_mid = (lh + rh) / 2.0
    ankle_mid = (la + ra) / 2.0

    scales = np.linalg.norm(hip_mid - ankle_mid, axis=1)
    scales[scales == 0] = 1.0

    lm_indices = sorted({int(c.split("_")[1]) for c in df.columns if c.startswith("x_")})
    coords = {}
    for i in lm_indices:
        arr = extract_landmark_coords(df, i)
        arr_norm = (arr - hip_mid) / scales[:, None]
        coords[i] = arr_norm
    return coords, hip_mid, ankle_mid, scales

In [5]:
coords_norm, hip_mid, ankle_mid, scales = normalize_landmarks(df, key_landmarks)
print(coords_norm)

{0: array([[-0.01719236, -0.720571  , -1.69023705],
       [-0.01676407, -0.7363521 , -1.71467867],
       [-0.01576668, -0.74231338, -1.46997552],
       ...,
       [ 0.03747705, -0.49129453, -2.25015316],
       [ 0.03784429, -0.49891664, -2.27264235],
       [ 0.0394172 , -0.51783275, -2.30004845]], shape=(9467, 3)), 1: array([[ 0.01959365, -0.75801256, -1.59586032],
       [ 0.02015723, -0.7734067 , -1.61849377],
       [ 0.0207184 , -0.77933952, -1.36190913],
       ...,
       [ 0.09849811, -0.52824357, -2.22381656],
       [ 0.09993189, -0.5364418 , -2.24311664],
       [ 0.1038879 , -0.55677842, -2.2709296 ]], shape=(9467, 3)), 2: array([[ 0.04622248, -0.75790397, -1.59594068],
       [ 0.04651552, -0.77344461, -1.61857599],
       [ 0.04691519, -0.77956623, -1.36209452],
       ...,
       [ 0.12846536, -0.52848111, -2.2235351 ],
       [ 0.13037672, -0.5366633 , -2.24281344],
       [ 0.13548139, -0.55693906, -2.27060067]], shape=(9467, 3)), 3: array([[ 0.06354136, -0.7579807 , -1.59579026],
       [ 0.06477222, -0.77325629, -1.61842474],
       [ 0.06534563, -0.77923081, -1.36205976],
       ...,
       [ 0.15198087, -0.5284305 , -2.22393843],
       [ 0.15426416, -0.53659187, -2.24316743],
       [ 0.16025372, -0.55681904, -2.27088839]], shape=(9467, 3)), 4: array([[-0.05921357, -0.75704809, -1.59845303],
       [-0.05932099, -0.77128923, -1.62225192],
       [-0.05834848, -0.7765499 , -1.37343815],
       ...,
       [ 0.01084783, -0.53107849, -2.20122266],
       [ 0.01087193, -0.53931105, -2.22062476],
       [ 0.01139122, -0.55987108, -2.24702116]], shape=(9467, 3)), 5: array([[-0.08329679, -0.75633103, -1.59836716],
       [-0.08377697, -0.76986681, -1.62216756],
       [-0.08302579, -0.77462903, -1.37333194],
       ...,
       [-0.01286522, -0.53413712, -2.20187799],
       [-0.01322085, -0.54240623, -2.22129442],
       [-0.01361834, -0.56308258, -2.24766913]], shape=(9467, 3)), 6: array([[-0.10832819, -0.75509535, -1.59815243],
       [-0.1089084 , -0.76831464, -1.62201691],
       [-0.10785742, -0.77272948, -1.37330765],
       ...,
       [-0.03392302, -0.53720898, -2.20234605],
       [-0.03461639, -0.54552216, -2.22180852],
       [-0.03582561, -0.56630968, -2.24819537]], shape=(9467, 3)), 7: array([[ 0.10030768, -0.74488383, -0.88408646],
       [ 0.10152017, -0.75693444, -0.89628955],
       [ 0.10134775, -0.76104685, -0.64119678],
       ...,
       [ 0.19872586, -0.52353635, -1.82365441],
       [ 0.20177633, -0.53151412, -1.83717662],
       [ 0.20959907, -0.55144829, -1.85439711]], shape=(9467, 3)), 8: array([[-0.1352663 , -0.73860413, -0.90635324],
       [-0.13650412, -0.74986344, -0.92760825],
       [-0.13628264, -0.75296115, -0.69723699],
       ...,
       [-0.04367372, -0.53757777, -1.7254653 ],
       [-0.04456258, -0.54580659, -1.73937919],
       [-0.04615519, -0.5665824 , -1.74964459]], shape=(9467, 3)), 9: array([[ 0.03281165, -0.68187338, -1.40753551],
       [ 0.03428996, -0.6974344 , -1.42841537],
       [ 0.03570933, -0.70350151, -1.19021532],
       ...,
       [ 0.08617821, -0.4509616 , -2.08055125],
       [ 0.08738268, -0.45777489, -2.10200915],
       [ 0.090789  , -0.47508164, -2.12495273]], shape=(9467, 3)), 10: array([[-0.05908014, -0.680956  , -1.41426388],
       [-0.05917081, -0.69571756, -1.43804642],
       [-0.05852197, -0.70125224, -1.20668845],
       ...,
       [-0.00562445, -0.45686553, -2.0511938 ],
       [-0.00608088, -0.46391036, -2.07305762],
       [-0.00635099, -0.48156387, -2.0939102 ]], shape=(9467, 3)), 11: array([[ 0.32455594, -0.52779001, -0.42871001],
       [ 0.32991841, -0.53570594, -0.41455935],
       [ 0.33099877, -0.53790347, -0.21091283],
       ...,
       [ 0.39464082, -0.32350064, -1.50376484],
       [ 0.4007804 , -0.32830469, -1.51331624],
       [ 0.41567575, -0.34106764, -1.52888663]], shape=(9467, 3)), 12: array([[-0.31389667, -0.53127258, -0.33279587],
       [-0.31793511, -0.5385326 , -0.38264006],
       [-0.31874912, -0.54050186, -0.22745657],
       ...,
       [-0.22891944, -0.39864029, -1.4346246 ],
       [-0.23319311, -0.4044153 , -1.4535076 ],
       [-0.24211085, -0.41964663, -1.47757452]], shape=(9467, 3)), 13: array([[ 0.40995822, -0.26072007, -0.17950015],
       [ 0.4165186 , -0.26482694, -0.16045305],
       [ 0.41697255, -0.26730634, -0.09627429],
       ...,
       [ 0.30090732, -0.04449258, -1.43687673],
       [ 0.30496599, -0.04489985, -1.44948441],
       [ 0.31643232, -0.04623639, -1.45828125]], shape=(9467, 3)), 14: array([[-0.38910242, -0.25915486, -0.0263439 ],
       [-0.39695971, -0.26345762, -0.07424829],
       [-0.40113836, -0.26527497,  0.01322514],
       ...,
       [-0.24474728, -0.13340809, -1.3226122 ],
       [-0.24881618, -0.13471133, -1.34091012],
       [-0.25789441, -0.13985914, -1.37058999]], shape=(9467, 3)), 15: array([[ 3.98372313e-01, -9.53066455e-03, -8.43525198e-01],
       [ 4.02922666e-01, -1.03063785e-02, -8.55463362e-01],
       [ 3.95213335e-01, -1.68552332e-02, -8.74238014e-01],
       ...,
       [-8.74432521e-04,  1.24587369e-01, -1.61900289e+00],
       [-1.12995700e-03,  1.26960882e-01, -1.64065356e+00],
       [-1.21992730e-03,  1.31987722e-01, -1.66115114e+00]],
      shape=(9467, 3)), 16: array([[-0.44237297, -0.02632448, -0.60681852],
       [-0.44794768, -0.02631896, -0.64248721],
       [-0.44838111, -0.02695277, -0.57161588],
       ...,
       [-0.17699269,  0.08735715, -1.51655469],
       [-0.17995134,  0.09074069, -1.53871955],
       [-0.18651025,  0.09460507, -1.58447593]], shape=(9467, 3)), 17: array([[ 0.43994919,  0.07319057, -1.0562897 ],
       [ 0.43971553,  0.07384747, -1.0707374 ],
       [ 0.42263775,  0.06979916, -1.10734992],
       ...,
       [-0.03021805,  0.20395496, -1.73147955],
       [-0.03123792,  0.2073938 , -1.75655945],
       [-0.0322893 ,  0.21584422, -1.77389821]], shape=(9467, 3)), 18: array([[-0.47179859,  0.0604906 , -0.79600665],
       [-0.47821216,  0.06064076, -0.83161618],
       [-0.47903738,  0.05967471, -0.77418904],
       ...,
       [-0.19067202,  0.16836385, -1.62749225],
       [-0.19350969,  0.1726575 , -1.65256055],
       [-0.20059718,  0.17925894, -1.7034135 ]], shape=(9467, 3)), 19: array([[ 0.39617556,  0.06863728, -1.28643002],
       [ 0.39471843,  0.06922424, -1.30417744],
       [ 0.37642544,  0.06440877, -1.32990687],
       ...,
       [-0.08710479,  0.18285419, -1.82057006],
       [-0.08870568,  0.1863222 , -1.8440177 ],
       [-0.09196952,  0.1937256 , -1.87526217]], shape=(9467, 3)), 20: array([[-0.44350673,  0.0548804 , -1.02351402],
       [-0.4506749 ,  0.05522553, -1.07199622],
       [-0.45185528,  0.05432028, -1.01379317],
       ...,
       [-0.15193093,  0.16770651, -1.69231237],
       [-0.15404487,  0.17169915, -1.71650463],
       [-0.15982119,  0.17827662, -1.76931271]], shape=(9467, 3)), 21: array([[ 0.36580737,  0.04124441, -0.94769998],
       [ 0.36742177,  0.0422738 , -0.96122656],
       [ 0.35345384,  0.03850157, -0.98154877],
       ...,
       [-0.08389879,  0.15361827, -1.65173397],
       [-0.0853848 ,  0.15683492, -1.67227048],
       [-0.08859296,  0.16317988, -1.69884141]], shape=(9467, 3)), 22: array([[-0.42088341,  0.02740669, -0.70999105],
       [-0.42789584,  0.03005893, -0.74976664],
       [-0.42926399,  0.03053922, -0.68012486],
       ...,
       [-0.13823068,  0.14150417, -1.54007545],
       [-0.14029303,  0.14551903, -1.56202259],
       [-0.14563714,  0.1511768 , -1.60880254]], shape=(9467, 3)), 23: array([[ 1.84689837e-01, -8.37840022e-04, -6.19055576e-02],
       [ 1.87835931e-01, -3.81031250e-04, -2.01054384e-02],
       [ 1.88599409e-01,  1.74678585e-04, -1.19702808e-02],
       ...,
       [ 1.56862581e-01,  1.70645056e-02, -4.93812965e-02],
       [ 1.59511932e-01,  1.72767596e-02, -4.70351351e-02],
       [ 1.65583624e-01,  1.79389266e-02, -4.80450288e-02]],
      shape=(9467, 3)), 24: array([[-1.84689837e-01,  8.37840022e-04,  6.19055576e-02],
       [-1.87835931e-01,  3.81031250e-04,  2.01054384e-02],
       [-1.88599409e-01, -1.74678585e-04,  1.19702808e-02],
       ...,
       [-1.56862581e-01, -1.70645056e-02,  4.93812965e-02],
       [-1.59511932e-01, -1.72767596e-02,  4.70351351e-02],
       [-1.65583624e-01, -1.79389266e-02,  4.80450288e-02]],
      shape=(9467, 3)), 25: array([[ 0.1993511 ,  0.3948136 , -0.12849194],
       [ 0.2040619 ,  0.40618704, -0.11152411],
       [ 0.2073742 ,  0.40850272, -0.10520085],
       ...,
       [-0.02795508,  0.33158913, -0.60702021],
       [-0.02763924,  0.33794519, -0.62139884],
       [-0.0256618 ,  0.35019027, -0.64891109]], shape=(9467, 3)), 26: array([[-0.23451027,  0.38751319, -0.06095891],
       [-0.22894204,  0.40554379, -0.13095265],
       [-0.2254354 ,  0.41003708, -0.14333175],
       ...,
       [-0.31686032,  0.2945117 , -0.56712476],
       [-0.32166187,  0.29914306, -0.61726788],
       [-0.33222742,  0.30904715, -0.67387603]], shape=(9467, 3)), 27: array([[0.18659864, 0.78953676, 0.57304767],
       [0.18936006, 0.80199688, 0.59174257],
       [0.19029095, 0.8032687 , 0.59622691],
       ...,
       [0.09146337, 0.17033887, 0.97626775],
       [0.09272411, 0.17298949, 0.98976728],
       [0.10366751, 0.17313861, 0.9938558 ]], shape=(9467, 3)), 28: array([[-0.22768385,  0.79712348,  0.64384234],
       [-0.23323806,  0.80788475,  0.59415619],
       [-0.23525312,  0.80832188,  0.58730771],
       ...,
       [-0.10993897,  0.14232601,  0.99905484],
       [-0.11458295,  0.14634142,  0.98445408],
       [-0.11515076,  0.14712766,  0.98030165]], shape=(9467, 3)), 29: array([[0.10995947, 0.85647915, 0.58549484],
       [0.11442058, 0.86498003, 0.60165384],
       [0.11766776, 0.86276539, 0.60545362],
       ...,
       [0.1165556 , 0.12910325, 1.16138429],
       [0.11752715, 0.13044742, 1.17787419],
       [0.12629413, 0.12795789, 1.18686502]], shape=(9467, 3)), 30: array([[-0.17499552,  0.86016907,  0.65579596],
       [-0.17803451,  0.87105324,  0.60471777],
       [-0.17870131,  0.87080633,  0.59812826],
       ...,
       [-0.06545839,  0.1036915 ,  1.18999121],
       [-0.0728043 ,  0.10636812,  1.18056078],
       [-0.07441086,  0.1060168 ,  1.18324029]], shape=(9467, 3)), 31: array([[ 0.24601007,  0.93087892, -0.22175745],
       [ 0.24936505,  0.95057792, -0.24237227],
       [ 0.24966261,  0.95459965, -0.25060239],
       ...,
       [ 0.09440353,  0.21082967,  1.50031747],
       [ 0.0937989 ,  0.2133228 ,  1.52696123],
       [ 0.10982221,  0.20974132,  1.56764304]], shape=(9467, 3)), 32: array([[-0.35231548,  0.92753904, -0.15978531],
       [-0.35748858,  0.94064996, -0.27035435],
       [-0.35919752,  0.94225999, -0.27378306],
       ...,
       [-0.09509217,  0.18548153,  1.57640205],
       [-0.10466398,  0.19285261,  1.57817525],
       [-0.09962526,  0.19785397,  1.61791079]], shape=(9467, 3))}

In [6]:
def smooth_coords(coords_dict, window=5):
    smoothed = {}
    for idx, arr in coords_dict.items():
        df_tmp = pd.DataFrame(arr, columns=["x","y","z"])
        df_s = df_tmp.rolling(window=window, center=True, min_periods=1).mean()
        smoothed[idx] = df_s.to_numpy()
    return smoothed

In [7]:
coords_s = smooth_coords(coords_norm)
print(coords_s)

{0: array([[-0.01657437, -0.73307883, -1.62496375],
       [-0.01567412, -0.73562911, -1.56885365],
       [-0.01505525, -0.73706947, -1.51750965],
       ...,
       [ 0.03834159, -0.50117863, -2.25582836],
       [ 0.03850386, -0.50548823, -2.27884771],
       [ 0.03824618, -0.50268131, -2.27428132]], shape=(9467, 3)), 1: array([[ 0.02015643, -0.77025293, -1.52542107],
       [ 0.02087592, -0.77270475, -1.46727875],
       [ 0.02123286, -0.77398287, -1.41556746],
       ...,
       [ 0.10051823, -0.53888653, -2.22903524],
       [ 0.10129985, -0.54351208, -2.25064576],
       [ 0.10077263, -0.54048793, -2.24595427]], shape=(9467, 3)), 2: array([[ 0.04655106, -0.77030494, -1.52553706],
       [ 0.04709605, -0.7728095 , -1.46741649],
       [ 0.04728286, -0.7740943 , -1.4157221 ],
       ...,
       [ 0.1311604 , -0.53910243, -2.22874301],
       [ 0.13215942, -0.54372461, -2.25034115],
       [ 0.13144115, -0.54069449, -2.24564974]], shape=(9467, 3)), 3: array([[ 0.06455307, -0.77015593, -1.52542492],
       [ 0.06526858, -0.77259289, -1.46733131],
       [ 0.06571937, -0.77382718, -1.41564423],
       ...,
       [ 0.15525597, -0.53902989, -2.22910674],
       [ 0.15638495, -0.5436489 , -2.25068908],
       [ 0.15549958, -0.5406138 , -2.24599809]], shape=(9467, 3)), 4: array([[-0.05896102, -0.76829574, -1.53138104],
       [-0.05803948, -0.77042776, -1.47452061],
       [-0.05721643, -0.77144686, -1.42230905],
       ...,
       [ 0.01125342, -0.54181386, -2.2053956 ],
       [ 0.01113314, -0.5464647 , -2.22751142],
       [ 0.01103699, -0.54342021, -2.22295619]], shape=(9467, 3)), 5: array([[-0.08336652, -0.76694229, -1.53128889],
       [-0.08250048, -0.76882355, -1.47441766],
       [-0.08169216, -0.76959809, -1.42220304],
       ...,
       [-0.0129205 , -0.54493306, -2.20604619],
       [-0.01327757, -0.54960783, -2.2281711 ],
       [-0.0132348 , -0.54654198, -2.22361385]], shape=(9467, 3)), 6: array([[-0.10836467, -0.76537983, -1.531159  ],
       [-0.10742557, -0.76710967, -1.47432582],
       [-0.10652669, -0.76772848, -1.42214519],
       ...,
       [-0.03439278, -0.54806101, -2.20654321],
       [-0.03494617, -0.55276243, -2.22867432],
       [-0.03478834, -0.54968027, -2.22411665]], shape=(9467, 3)), 7: array([[ 0.10105854, -0.75428837, -0.80719093],
       [ 0.10143911, -0.75587152, -0.75030553],
       [ 0.10165375, -0.75639468, -0.70512801],
       ...,
       [ 0.20302408, -0.53397819, -1.8247293 ],
       [ 0.20452562, -0.53853597, -1.84043891],
       [ 0.20336709, -0.53549958, -1.83840938]], shape=(9467, 3)), 8: array([[-0.13601768, -0.74714291, -0.84373283],
       [-0.13528071, -0.74832515, -0.79095363],
       [-0.13432722, -0.74849717, -0.74218655],
       ...,
       [-0.0442279 , -0.54838064, -1.72137339],
       [-0.04495786, -0.55307966, -1.73987907],
       [-0.04479716, -0.54998892, -1.73816303]], shape=(9467, 3)), 9: array([[ 0.03427031, -0.69426976, -1.3420554 ],
       [ 0.03531057, -0.69679196, -1.2874995 ],
       [ 0.03623044, -0.6980943 , -1.23958914],
       ...,
       [ 0.08806027, -0.45995083, -2.08459111],
       [ 0.08864805, -0.4638819 , -2.10595718],
       [ 0.08811663, -0.46127271, -2.10250438]], shape=(9467, 3)), 10: array([[-0.05892431, -0.69264193, -1.35299959],
       [-0.05812107, -0.69493956, -1.29961233],
       [-0.05749919, -0.69606735, -1.25062336],
       ...,
       [-0.00553226, -0.46603706, -2.05381928],
       [-0.00592185, -0.47005051, -2.07579501],
       [-0.00601877, -0.46744659, -2.07272054]], shape=(9467, 3)), 11: array([[ 0.32849104, -0.53379981, -0.35139407],
       [ 0.32913708, -0.53467857, -0.29974228],
       [ 0.32921335, -0.53492652, -0.26763909],
       ...,
       [ 0.40311533, -0.32994088, -1.50422029],
       [ 0.40609882, -0.3328177 , -1.51774663],
       [ 0.40369899, -0.33095766, -1.51532257]], shape=(9467, 3)), 12: array([[-0.3168603 , -0.53676901, -0.3142975 ],
       [-0.31646275, -0.53754827, -0.28050562],
       [-0.31542914, -0.53773925, -0.2482175 ],
       ...,
       [-0.23325963, -0.40647263, -1.43729624],
       [-0.23577725, -0.40991758, -1.45481242],
       [-0.23474113, -0.40756741, -1.45523557]], shape=(9467, 3)), 13: array([[ 0.41448312, -0.26428445, -0.14540917],
       [ 0.41456611, -0.26526043, -0.1091905 ],
       [ 0.41323771, -0.26607821, -0.09596499],
       ...,
       [ 0.3064198 , -0.0451146 , -1.42889568],
       [ 0.30895048, -0.04551351, -1.4466789 ],
       [ 0.30743521, -0.0452096 , -1.44821413]], shape=(9467, 3)), 14: array([[-0.3957335 , -0.26262915, -0.02912235],
       [-0.39688531, -0.26367119, -0.00865032],
       [-0.39719501, -0.2645589 ,  0.00338019],
       ...,
       [-0.2492451 , -0.13610098, -1.32473246],
       [-0.25175185, -0.137013  , -1.34483464],
       [-0.25048596, -0.13599285, -1.3447041 ]], shape=(9467, 3)), 15: array([[ 3.98836104e-01, -1.22307587e-02, -8.57742191e-01],
       [ 3.96018987e-01, -1.41244236e-02, -8.36413437e-01],
       [ 3.90256016e-01, -1.61729486e-02, -8.42875910e-01],
       ...,
       [-6.49717667e-04,  1.27243669e-01, -1.61382934e+00],
       [-9.83692622e-04,  1.28477875e-01, -1.63916006e+00],
       [-1.07477227e-03,  1.27845324e-01, -1.64026920e+00]],
      shape=(9467, 3)), 16: array([[-0.44623392, -0.02653207, -0.60697387],
       [-0.44569582, -0.02691366, -0.5873677 ],
       [-0.44434887, -0.02765154, -0.57935829],
       ...,
       [-0.18037954,  0.09001806, -1.52720414],
       [-0.18219108,  0.09100861, -1.55154452],
       [-0.18115143,  0.09090097, -1.54658339]], shape=(9467, 3)), 17: array([[ 0.43410082,  0.07227907, -1.07812568],
       [ 0.42854952,  0.07092586, -1.05876782],
       [ 0.41987834,  0.0691175 , -1.06880421],
       ...,
       [-0.03066077,  0.2082516 , -1.72500127],
       [-0.031278  ,  0.21021072, -1.75264255],
       [-0.03124842,  0.20906433, -1.75397907]], shape=(9467, 3)), 18: array([[-0.47634938,  0.06026869, -0.80060396],
       [-0.47615428,  0.05970542, -0.78328761],
       [-0.47505828,  0.05867623, -0.77961498],
       ...,
       [-0.1940341 ,  0.17237837, -1.64041225],
       [-0.19601149,  0.17404627, -1.66708287],
       [-0.19492629,  0.17342676, -1.66115543]], shape=(9467, 3)), 19: array([[ 0.38910648,  0.06742343, -1.30683811],
       [ 0.38353724,  0.06587618, -1.28471904],
       [ 0.37522486,  0.06386322, -1.29037037],
       ...,
       [-0.08856652,  0.18680606, -1.82090552],
       [-0.08965815,  0.18859532, -1.84864367],
       [-0.08926   ,  0.187634  , -1.84661664]], shape=(9467, 3)), 20: array([[-0.44867897,  0.05480873, -1.03643447],
       [-0.44861375,  0.05433251, -1.0194471 ],
       [-0.44761663,  0.05341948, -1.01388405],
       ...,
       [-0.15457382,  0.17157843, -1.70629921],
       [-0.15615867,  0.17321821, -1.73297402],
       [-0.15526566,  0.17256076, -1.72604323]], shape=(9467, 3)), 21: array([[ 0.36222766,  0.04067326, -0.96349177],
       [ 0.35806312,  0.03955742, -0.94245633],
       [ 0.3509351 ,  0.03790469, -0.9481878 ],
       ...,
       [-0.08529659,  0.15704281, -1.64883113],
       [-0.08634977,  0.15856654, -1.67455   ],
       [-0.08595885,  0.15787769, -1.67428195]], shape=(9467, 3)), 22: array([[-0.42601441,  0.02933495, -0.71329418],
       [-0.42610748,  0.02959201, -0.69410429],
       [-0.42525908,  0.02922817, -0.68632713],
       ...,
       [-0.14063191,  0.1450387 , -1.55130212],
       [-0.14213117,  0.14649534, -1.57566181],
       [-0.14138695,  0.14606667, -1.5703002 ]], shape=(9467, 3)), 23: array([[ 1.87041726e-01, -3.48064229e-04, -3.13270923e-02],
       [ 1.87398044e-01, -3.03050323e-05, -2.43508535e-02],
       [ 1.87440628e-01,  2.37954700e-04, -2.03401790e-02],
       ...,
       [ 1.59994513e-01,  1.73904705e-02, -4.92397920e-02],
       [ 1.61483771e-01,  1.75249517e-02, -4.87894287e-02],
       [ 1.60652712e-01,  1.74267306e-02, -4.81538201e-02]],
      shape=(9467, 3)), 24: array([[-1.87041726e-01,  3.48064229e-04,  3.13270923e-02],
       [-1.87398044e-01,  3.03050323e-05,  2.43508535e-02],
       [-1.87440628e-01, -2.37954700e-04,  2.03401790e-02],
       ...,
       [-1.59994513e-01, -1.73904705e-02,  4.92397920e-02],
       [-1.61483771e-01, -1.75249517e-02,  4.87894287e-02],
       [-1.60652712e-01, -1.74267306e-02,  4.81538201e-02]],
      shape=(9467, 3)), 25: array([[ 0.20359573,  0.40316779, -0.1150723 ],
       [ 0.20538217,  0.40433427, -0.10918651],
       [ 0.20706893,  0.40407564, -0.10224959],
       ...,
       [-0.02649805,  0.33876876, -0.62057464],
       [-0.02709434,  0.34162409, -0.63140277],
       [-0.02708537,  0.3399082 , -0.62577672]], shape=(9467, 3)), 26: array([[-0.22962924,  0.40103135, -0.11174777],
       [-0.22719907,  0.4029419 , -0.12021634],
       [-0.22485064,  0.40313801, -0.12338743],
       ...,
       [-0.32120284,  0.30100024, -0.60246798],
       [-0.32493197,  0.30313442, -0.63470156],
       [-0.3235832 ,  0.30090064, -0.61942289]], shape=(9467, 3)), 27: array([[0.18874988, 0.79826745, 0.58700572],
       [0.18966613, 0.79846398, 0.59163145],
       [0.19035501, 0.79698726, 0.59741643],
       ...,
       [0.0972453 , 0.17238111, 0.9798667 ],
       [0.09774919, 0.17294351, 0.98717869],
       [0.09595166, 0.17215566, 0.98663028]], shape=(9467, 3)), 28: array([[-0.23205834,  0.80444337,  0.60843541],
       [-0.23223297,  0.80417535,  0.60396938],
       [-0.23174032,  0.80228095,  0.60269886],
       ...,
       [-0.11150493,  0.14031708,  0.99546164],
       [-0.11314127,  0.14360325,  0.98754292],
       [-0.11322423,  0.14526503,  0.98793686]], shape=(9467, 3)), 29: array([[0.11401594, 0.86140819, 0.5975341 ],
       [0.11581651, 0.86005076, 0.60173748],
       [0.11728648, 0.85681088, 0.60738817],
       ...,
       [0.12267462, 0.12970973, 1.16762377],
       [0.12248834, 0.12966489, 1.17704263],
       [0.12012563, 0.12916952, 1.1753745 ]], shape=(9467, 3)), 30: array([[-0.17724378,  0.86734288,  0.61954733],
       [-0.17690399,  0.86670197,  0.61521437],
       [-0.17615543,  0.86427901,  0.61452818],
       ...,
       [-0.0652013 ,  0.10377921,  1.19177004],
       [-0.06840697,  0.10486985,  1.18628042],
       [-0.07089118,  0.10535881,  1.18459743]], shape=(9467, 3)), 31: array([[ 0.24834591,  0.94535217, -0.23824404],
       [ 0.24907467,  0.94681807, -0.24082865],
       [ 0.24943531,  0.94604211, -0.23898782],
       ...,
       [ 0.09738667,  0.21169633,  1.52145517],
       [ 0.10090664,  0.21172616,  1.53655007],
       [ 0.09934155,  0.21129793,  1.53164058]], shape=(9467, 3)), 32: array([[-0.35633386,  0.93681633, -0.23464091],
       [-0.35609556,  0.93698171, -0.241317  ],
       [-0.35516705,  0.93531333, -0.24155358],
       ...,
       [-0.09345864,  0.18685083,  1.59790439],
       [-0.09672911,  0.19027443,  1.6014536 ],
       [-0.0997938 ,  0.1920627 ,  1.59082936]], shape=(9467, 3))}

In [8]:
def compute_velocities(smoothed_coords, fps=None):
    vel = {}
    for i, arr in smoothed_coords.items():
        d = np.vstack([np.zeros(3), np.diff(arr, axis=0)])
        if fps is not None:
            d = d * fps
        speed = np.linalg.norm(d, axis=1)
        vel[i] = {"vel_vec": d, "speed": speed}
    return vel

In [9]:
velocities = compute_velocities(coords_s, fps=30)
print(velocities)

{0: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02700731, -0.07650855,  1.683303  ],
       [ 0.01856614, -0.04321073,  1.54032   ],
       ...,
       [-0.00231665, -0.03588804, -0.18350385],
       [ 0.00486794, -0.12928799, -0.69058037],
       [-0.00773024,  0.08420755,  0.13699155]], shape=(9467, 3)), 'speed': array([0.        , 1.68525723, 1.54103782, ..., 0.1869946 , 0.70259543,
       0.16098868], shape=(9467,))}, 1: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02158478, -0.07355455,  1.74426958],
       [ 0.0107083 , -0.03834369,  1.55133884],
       ...,
       [ 0.00559194, -0.03788845, -0.16660072],
       [ 0.02344855, -0.13876651, -0.64831566],
       [-0.01581647,  0.09072459,  0.14074495]], shape=(9467, 3)), 'speed': array([0.        , 1.74595319, 1.55184957, ..., 0.1709462 , 0.66341478,
       0.16819706], shape=(9467,))}, 2: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01634966, -0.07513684,  1.74361735],
       [ 0.00560412, -0.03854419,  1.55083163],
       ...,
       [ 0.00622754, -0.03725818, -0.16637834],
       [ 0.02997064, -0.13866522, -0.64794419],
       [-0.02154786,  0.09090343,  0.14074235]], shape=(9467, 3)), 'speed': array([0.        , 1.7453121 , 1.55132066, ..., 0.17061273, 0.66329327,
       0.16892647], shape=(9467,))}, 3: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02146548, -0.0731086 ,  1.74280829],
       [ 0.01352369, -0.03702894,  1.55061245],
       ...,
       [ 0.00457519, -0.03679674, -0.16584517],
       [ 0.03386928, -0.13857043, -0.64747017],
       [-0.02656089,  0.09105295,  0.14072969]], shape=(9467, 3)), 'speed': array([0.        , 1.74447309, 1.55111347, ..., 0.16993985, 0.66299812,
       0.16970848], shape=(9467,))}, 4: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02764617, -0.06396052,  1.70581282],
       [ 0.0246914 , -0.03057318,  1.56634671],
       ...,
       [-0.0058637 , -0.03851927, -0.17388258],
       [-0.00360858, -0.13952512, -0.66347468],
       [-0.00288427,  0.09133471,  0.13665678]], shape=(9467, 3)), 'speed': array([0.        , 1.70723537, 1.56683962, ..., 0.17819447, 0.67799626,
       0.16439411], shape=(9467,))}, 5: {'vel_vec': array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.59811260e-02, -5.64377922e-02,  1.70613680e+00],
       [ 2.42494447e-02, -2.32360810e-02,  1.56643860e+00],
       ...,
       [-8.54569188e-03, -3.84446835e-02, -1.74104618e-01],
       [-1.07122917e-02, -1.40242975e-01, -6.63747364e-01],
       [ 1.28311806e-03,  9.19755126e-02,  1.36717705e-01]],
      shape=(9467, 3)), 'speed': array([0.        , 1.70726771, 1.56679859, ..., 0.17850334, 0.67848612,
       0.16478129], shape=(9467,))}, 6: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02817292, -0.05189542,  1.70499536],
       [ 0.02696661, -0.01856412,  1.56541897],
       ...,
       [-0.01019583, -0.03842075, -0.17443417],
       [-0.01660167, -0.14104287, -0.66393335],
       [ 0.00473479,  0.0924648 ,  0.13673023]], shape=(9467, 3)), 'speed': array([0.        , 1.70601759, 1.56576128, ..., 0.17890609, 0.67895228,
       0.16512817], shape=(9467,))}, 7: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01141736, -0.04749442,  1.70656196],
       [ 0.006439  , -0.0156948 ,  1.35532554],
       ...,
       [ 0.0070592 , -0.03428937, -0.09028976],
       [ 0.04504613, -0.13673326, -0.47128849],
       [-0.0347559 ,  0.09109158,  0.06088598]], shape=(9467, 3)), 'speed': array([0.        , 1.70726091, 1.3554317 , ..., 0.09683922, 0.49278594,
       0.11494673], shape=(9467,))}, 8: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02210924, -0.0354673 ,  1.58337584],
       [ 0.02860479, -0.00516074,  1.46301252],
       ...,
       [-0.0144078 , -0.03739951, -0.1365595 ],
       [-0.0218988 , -0.14097064, -0.55517035],
       [ 0.00482085,  0.09272235,  0.05148139]], shape=(9467, 3)), 'speed': array([0.        , 1.58392733, 1.46330123, ..., 0.14231938, 0.57320712,
       0.10616501], shape=(9467,))}, 9: {'vel_vec': array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.12077791e-02, -7.56658426e-02,  1.63667695e+00],
       [ 2.75960866e-02, -3.90703094e-02,  1.43731082e+00],
       ...,
       [ 1.07588649e-03, -3.09355498e-02, -1.62618535e-01],
       [ 1.76335767e-02, -1.17932294e-01, -6.40982068e-01],
       [-1.59426820e-02,  7.82758239e-02,  1.03584185e-01]],
      shape=(9467, 3)), 'speed': array([0.        , 1.63872227, 1.43810654, ..., 0.16553838, 0.65197928,
       0.13080886], shape=(9467,))}, 10: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02409699, -0.06892878,  1.60161757],
       [ 0.01865642, -0.03383368,  1.46966928],
       ...,
       [-0.01314873, -0.03395772, -0.17393866],
       [-0.01168757, -0.12040355, -0.6592717 ],
       [-0.00290774,  0.07811767,  0.09223398]], shape=(9467, 3)), 'speed': array([0.        , 1.60328123, 1.47017705, ..., 0.17770952, 0.67027814,
       0.12090464], shape=(9467,))}, 11: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01938132, -0.02636291,  1.54955351],
       [ 0.00228806, -0.00743834,  0.96309584],
       ...,
       [ 0.0082621 , -0.02730737, -0.0471335 ],
       [ 0.08950469, -0.08630469, -0.40579009],
       [-0.07199482,  0.0558013 ,  0.07272166]], shape=(9467, 3)), 'speed': array([0.        , 1.54989894, 0.96312728, ..., 0.05509557, 0.42441158,
       0.11655676], shape=(9467,))}, 12: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01192655, -0.02337772,  1.01375626],
       [ 0.03100847, -0.00572945,  0.96864372],
       ...,
       [-0.03559628, -0.02683374, -0.18398711],
       [-0.07552868, -0.10334845, -0.52548549],
       [ 0.03108364,  0.07050526, -0.01269463]], shape=(9467, 3)), 'speed': array([0.        , 1.01409591, 0.96915685, ..., 0.18931033, 0.54085163,
       0.07809186], shape=(9467,))}, 13: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.00248966, -0.02927928,  1.08655987],
       [-0.03985212, -0.02453357,  0.39676537],
       ...,
       [ 0.02463984, -0.00629677, -0.18386459],
       [ 0.0759204 , -0.01196732, -0.53349664],
       [-0.04545814,  0.00911709, -0.04605686]], shape=(9467, 3)), 'speed': array([0.        , 1.08695714, 0.39951577, ..., 0.18561509, 0.53900445,
       0.06535135], shape=(9467,))}, 14: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.03455434, -0.03126119,  0.61416103],
       [-0.00929105, -0.02663129,  0.36091518],
       ...,
       [-0.02819716, -0.00092336, -0.3273244 ],
       [-0.07520245, -0.02736067, -0.6030655 ],
       [ 0.0379767 ,  0.03060441,  0.00391607]], shape=(9467, 3)), 'speed': array([0.        , 0.61592616, 0.36201563, ..., 0.32853797, 0.60835188,
       0.04893052], shape=(9467,))}, 15: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.08451352, -0.05680995,  0.63986262],
       [-0.17288912, -0.06145575, -0.19387417],
       ...,
       [-0.00881137,  0.01117478, -0.37060586],
       [-0.01001925,  0.03702619, -0.75992157],
       [-0.00273239, -0.01897653, -0.03327417]], shape=(9467, 3)), 'speed': array([0.        , 0.64791518, 0.26693567, ..., 0.37087898, 0.76088903,
       0.03840241], shape=(9467,))}, 16: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01614297, -0.01144774,  0.58818501],
       [ 0.04040852, -0.02213628,  0.24028242],
       ...,
       [-0.01956428,  0.01649473, -0.43273633],
       [-0.05434641,  0.02971644, -0.73021125],
       [ 0.03118969, -0.00322925,  0.14883388]], shape=(9467, 3)), 'speed': array([0.        , 0.58851784, 0.24465998, ..., 0.4334923 , 0.73283359,
       0.15210111], shape=(9467,))}, 17: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.16653894, -0.04059632,  0.58073557],
       [-0.26013552, -0.05425064, -0.30109171],
       ...,
       [-0.01156213,  0.01843302, -0.39036438],
       [-0.01851697,  0.05877377, -0.82923843],
       [ 0.00088734, -0.03439185, -0.0400958 ]], shape=(9467, 3)), 'speed': array([0.        , 0.60550564, 0.40158416, ..., 0.39097034, 0.83152487,
       0.05283238], shape=(9467,))}, 18: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.00585287, -0.01689813,  0.51949027],
       [ 0.03288003, -0.03087563,  0.11017908],
       ...,
       [-0.02158415,  0.01965616, -0.48730147],
       [-0.05932173,  0.0500371 , -0.80011843],
       [ 0.03255578, -0.01858522,  0.17782307]], shape=(9467, 3)), 'speed': array([0.        , 0.51979799, 0.1190539 , ..., 0.48817514, 0.8038733 ,
       0.18173149], shape=(9467,))}, 19: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.16707721, -0.0464174 ,  0.66357215],
       [-0.2493714 , -0.06038904, -0.16954009],
       ...,
       [-0.01592004,  0.01771487, -0.39962806],
       [-0.03274877,  0.05367772, -0.8321445 ],
       [ 0.01194453, -0.02883955,  0.06081069]], shape=(9467, 3)), 'speed': array([0.        , 0.68585521, 0.30753337, ..., 0.40033717, 0.83451677,
       0.06835446], shape=(9467,))}, 20: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.00195643, -0.01428665,  0.50962098],
       [ 0.02991384, -0.02739101,  0.16689143],
       ...,
       [-0.01504215,  0.01841117, -0.46600793],
       [-0.04754555,  0.04919345, -0.80024419],
       [ 0.02679034, -0.0197236 ,  0.20792354]], shape=(9467, 3)), 'speed': array([0.        , 0.50982495, 0.17174939, ..., 0.46661401, 0.80316333,
       0.21056814], shape=(9467,))}, 21: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.12493637, -0.03347504,  0.63106325],
       [-0.21384045, -0.04958197, -0.17194419],
       ...,
       [-0.01586733,  0.0172053 , -0.3748103 ],
       [-0.03159544,  0.04571201, -0.77156605],
       [ 0.01172766, -0.02066545,  0.00804139]], shape=(9467, 3)), 'speed': array([0.        , 0.64418204, 0.27883851, ..., 0.37554035, 0.77356449,
       0.02508512], shape=(9467,))}, 22: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.00279211,  0.00771187,  0.57569671],
       [ 0.02545188, -0.01091524,  0.23331491],
       ...,
       [-0.01576249,  0.01925574, -0.42646086],
       [-0.0449778 ,  0.04369914, -0.73079067],
       [ 0.02232679, -0.01286025,  0.16084829]], shape=(9467, 3)), 'speed': array([0.        , 0.57575513, 0.23495274, ..., 0.42718627, 0.73347639,
       0.16289888], shape=(9467,))}, 23: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01068955,  0.00953278,  0.20928716],
       [ 0.00127751,  0.00804779,  0.12032024],
       ...,
       [ 0.01467146, -0.00036225,  0.02166044],
       [ 0.04467776,  0.00403444,  0.0135109 ],
       [-0.02493177, -0.00294663,  0.01906826]], shape=(9467, 3)), 'speed': array([0.        , 0.20977668, 0.12059585, ..., 0.02616405, 0.04685001,
       0.03152577], shape=(9467,))}, 24: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.01068955, -0.00953278, -0.20928716],
       [-0.00127751, -0.00804779, -0.12032024],
       ...,
       [-0.01467146,  0.00036225, -0.02166044],
       [-0.04467776, -0.00403444, -0.0135109 ],
       [ 0.02493177,  0.00294663, -0.01906826]], shape=(9467, 3)), 'speed': array([0.        , 0.20977668, 0.12059585, ..., 0.02616405, 0.04685001,
       0.03152577], shape=(9467,))}, 25: {'vel_vec': array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.35930016e-02,  3.49944330e-02,  1.76573700e-01],
       [ 5.06029645e-02, -7.75876244e-03,  2.08107470e-01],
       ...,
       [ 4.83106067e-03,  2.72724406e-02, -1.94905853e-01],
       [-1.78887111e-02,  8.56600596e-02, -3.24843902e-01],
       [ 2.68886831e-04, -5.14768117e-02,  1.68781498e-01]],
      shape=(9467, 3)), 'speed': array([0.        , 0.18781664, 0.21431187, ..., 0.19686395, 0.33642416,
       0.17645716], shape=(9467,))}, 26: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.07290506,  0.05731633, -0.25405711],
       [ 0.07045291,  0.00588324, -0.09513282],
       ...,
       [-0.0445724 ,  0.0063512 , -0.86148531],
       [-0.1118739 ,  0.06402534, -0.96700721],
       [ 0.04046303, -0.06701349,  0.45836004]], shape=(9467, 3)), 'speed': array([0.        , 0.27045392, 0.11852628, ..., 0.86266098, 0.97556033,
       0.46499676], shape=(9467,))}, 27: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02748741,  0.00589582,  0.13877191],
       [ 0.02066647, -0.04430138,  0.17354953],
       ...,
       [-0.04064109,  0.03412986,  0.21916687],
       [ 0.01511685,  0.01687198,  0.21935989],
       [-0.05392591, -0.0236355 , -0.0164525 ]], shape=(9467, 3)), 'speed': array([0.        , 0.14159082, 0.18030295, ..., 0.22550091, 0.22052651,
       0.06113367], shape=(9467,))}, 28: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [-0.00523898, -0.00804066, -0.13398102],
       [ 0.01477955, -0.05683184, -0.03811541],
       ...,
       [ 0.00919569,  0.33940042, -0.27388957],
       [-0.04909001,  0.09858519, -0.23756154],
       [-0.00248875,  0.04985332,  0.01181801]], shape=(9467, 3)), 'speed': array([0.        , 0.13432428, 0.0700077 , ..., 0.43622552, 0.26184796,
       0.05129535], shape=(9467,))}, 29: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.05401718, -0.04072296,  0.1261015 ],
       [ 0.04409921, -0.09719627,  0.16952068],
       ...,
       [-0.06305513,  0.03101624,  0.27155   ],
       [-0.0055884 , -0.00134516,  0.28256594],
       [-0.07088143, -0.0148613 , -0.05004397]], shape=(9467, 3)), 'speed': array([0.        , 0.14310068, 0.20032252, ..., 0.28049485, 0.2826244 ,
       0.08803087], shape=(9467,))}, 30: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.01019359, -0.01922711, -0.12998885],
       [ 0.02245691, -0.07268889, -0.02058563],
       ...,
       [-0.11499596,  0.03181576, -0.20267733],
       [-0.09616993,  0.03271911, -0.16468836],
       [-0.07452655,  0.01466874, -0.05048987]], shape=(9467, 3)), 'speed': array([0.        , 0.13179792, 0.07881469, ..., 0.23519017, 0.19349793,
       0.09120639], shape=(9467,))}, 31: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.02186257,  0.04397728, -0.07753843],
       [ 0.01081935, -0.02327904,  0.0552249 ],
       ...,
       [-0.07468644,  0.03433164,  0.1933738 ],
       [ 0.10559904,  0.00089481,  0.45284697],
       [-0.04695277, -0.01284698, -0.14728484]], shape=(9467, 3)), 'speed': array([0.        , 0.09178334, 0.0608996 , ..., 0.21011938, 0.46499714,
       0.1551207 ], shape=(9467,))}, 32: {'vel_vec': array([[ 0.        ,  0.        ,  0.        ],
       [ 0.00714889,  0.00496142, -0.20028269],
       [ 0.02785531, -0.05005143, -0.00709762],
       ...,
       [-0.1150471 ,  0.09776829, -0.18625917],
       [-0.09811418,  0.10270799,  0.1064762 ],
       [-0.09194079,  0.05364819, -0.31872711]], shape=(9467, 3)), 'speed': array([0.        , 0.20047164, 0.05771863, ..., 0.23976437, 0.17751762,
       0.33603304], shape=(9467,))}}

In [10]:
def angle_between_vectors(a, b):
    dot = np.sum(a*b, axis=1)
    na = np.linalg.norm(a, axis=1)
    nb = np.linalg.norm(b, axis=1)
    cos = dot / (na * nb + 1e-8)
    cos = np.clip(cos, -1.0, 1.0)
    return np.arccos(cos)

def compute_joint_angles(smoothed_coords, key_landmarks):
    kl = key_landmarks

    hipL = smoothed_coords[kl['Cadera Izq']]
    hipR = smoothed_coords[kl['Cadera Der']]
    kneeL = smoothed_coords[kl['Rodilla Izq']]
    kneeR = smoothed_coords[kl['Rodilla Der']]
    ankleL = smoothed_coords[kl['Tobillo Izq']]
    ankleR = smoothed_coords[kl['Tobillo Der']]


    shoulderL = smoothed_coords[kl['Hombro Izq']]
    shoulderR = smoothed_coords[kl['Hombro Der']]
    elbowL = smoothed_coords[kl['Codo Izq']]
    elbowR = smoothed_coords[kl['Codo Der']]


    kneeL_ang = angle_between_vectors(hipL - kneeL, ankleL - kneeL)
    kneeR_ang = angle_between_vectors(hipR - kneeR, ankleR - kneeR)
    hipL_ang = angle_between_vectors(kneeL - hipL, ankleL - hipL)
    hipR_ang = angle_between_vectors(kneeR - hipR, ankleR - hipR)


    elbowL_ang = angle_between_vectors(shoulderL - elbowL, hipL - elbowL)
    elbowR_ang = angle_between_vectors(shoulderR - elbowR, hipR - elbowR)
    shoulderL_ang = angle_between_vectors(elbowL - shoulderL, hipL - shoulderL)
    shoulderR_ang = angle_between_vectors(elbowR - shoulderR, hipR - shoulderR)

    return {
        "rodilla_Izq": kneeL_ang,
        "rodilla_Der": kneeR_ang,
        "cadera_Izq": hipL_ang,
        "cadera_Der": hipR_ang,
        "codo_Izq": elbowL_ang,
        "codo_Der": elbowR_ang,
        "hombro_Izq": shoulderL_ang,
        "hombro_Der": shoulderR_ang
    }

In [11]:
angles = compute_joint_angles(coords_s, key_landmarks)
print(angles)

{'rodilla_Izq': array([1.87766148, 1.87504872, 1.8808912 , ..., 0.44882056, 0.44391129,
       0.4461476 ], shape=(9467,)), 'rodilla_Der': array([1.73788971, 1.73211135, 1.73125039, ..., 0.35982332, 0.34585999,
       0.35397377], shape=(9467,)), 'cadera_Izq': array([0.86407949, 0.86455768, 0.86043683, ..., 2.4051887 , 2.41021104,
       2.40846555], shape=(9467,)), 'cadera_Der': array([0.96412789, 0.96761301, 0.96860049, ..., 2.50589893, 2.51757952,
       2.5091374 ], shape=(9467,)), 'codo_Izq': array([2.19589567, 2.16141154, 2.16125425, ..., 1.89181866, 1.87618886,
       1.86442542], shape=(9467,)), 'codo_Der': array([2.12893519, 2.07417204, 2.05073544, ..., 2.04566286, 2.03370858,
       2.03661106], shape=(9467,)), 'hombro_Izq': array([0.48474741, 0.50418587, 0.5114324 , ..., 1.05437862, 1.06996769,
       1.08235422], shape=(9467,)), 'hombro_Der': array([0.46000191, 0.48874122, 0.50959804, ..., 0.92554212, 0.93759058,
       0.93545545], shape=(9467,))}

In [12]:
def trunk_inclination(smoothed_coords, key_landmarks):
    hipL = smoothed_coords[key_landmarks['Cadera Izq']]
    hipR = smoothed_coords[key_landmarks['Cadera Der']]
    shoulderL = smoothed_coords[key_landmarks['Hombro Izq']]
    shoulderR = smoothed_coords[key_landmarks['Hombro Der']]

    hip_mid = (hipL + hipR) / 2.0
    shoulder_mid = (shoulderL + shoulderR) / 2.0
    vec = shoulder_mid - hip_mid
    vertical = np.tile(np.array([0.0, -1.0, 0.0]), (vec.shape[0], 1))
    ang = angle_between_vectors(vec, vertical)
    return ang

In [13]:
trunk_ang = trunk_inclination(coords_s, key_landmarks)
print(trunk_ang)

[0.55637134 0.49613198 0.44839942 ... 1.32587856 1.32633088 1.32749955]

In [14]:
feature_parts = []
selected_indices = set(key_landmarks.values())
idx_to_name = {v: k.replace(" ", "_") for k, v in key_landmarks.items()}

for idx, arr in coords_s.items():
    if idx not in selected_indices:
        continue
    name = idx_to_name[idx]
    part = pd.DataFrame({
        f"x_{name}": arr[:, 0],
        f"y_{name}": arr[:, 1],
        f"z_{name}": arr[:, 2],
        f"velocidad_{name}": velocities[idx]["speed"]
    }, index=df.index)
    feature_parts.append(part)

angle_df = pd.DataFrame(
    {f"{name}_ang": np.degrees(arr) for name, arr in angles.items()},
    index=df.index
)
feature_parts.append(angle_df)

feature_parts.append(
    pd.DataFrame({"inclinacion_tronco_ang": np.degrees(trunk_ang)}, index=df.index)
)

features = pd.concat(feature_parts, axis=1)

if "action" in df.columns:
    features["accion"] = df["action"].values
if "speed" in df.columns:
    features["velocidad_accion"] = df["speed"].values

features.columns = features.columns.str.lower()

features.head()

,x_hombro_izq,y_hombro_izq,z_hombro_izq,velocidad_hombro_izq,x_hombro_der,y_hombro_der,z_hombro_der,velocidad_hombro_der,x_codo_izq,y_codo_izq,z_codo_izq,velocidad_codo_izq,x_codo_der,y_codo_der,z_codo_der,velocidad_codo_der,x_cadera_izq,y_cadera_izq,z_cadera_izq,velocidad_cadera_izq,x_cadera_der,y_cadera_der,z_cadera_der,velocidad_cadera_der,x_rodilla_izq,y_rodilla_izq,z_rodilla_izq,velocidad_rodilla_izq,x_rodilla_der,y_rodilla_der,z_rodilla_der,velocidad_rodilla_der,x_tobillo_izq,y_tobillo_izq,z_tobillo_izq,velocidad_tobillo_izq,x_tobillo_der,y_tobillo_der,z_tobillo_der,velocidad_tobillo_der,rodilla_izq_ang,rodilla_der_ang,cadera_izq_ang,cadera_der_ang,codo_izq_ang,codo_der_ang,hombro_izq_ang,hombro_der_ang,inclinacion_tronco_ang,accion,velocidad_accion
0,0.328491,-0.533800,-0.351394,0.000000,-0.316860,-0.536769,-0.314297,0.000000,0.414483,-0.264284,-0.145409,0.000000,-0.395733,-0.262629,-0.029122,0.000000,0.187042,-0.000348,-0.031327,0.000000,-0.187042,0.000348,0.031327,0.000000,0.203596,0.403168,-0.115072,0.000000,-0.229629,0.401031,-0.111748,0.000000,0.188750,0.798267,0.587006,0.000000,-0.232058,0.804443,0.608435,0.000000,107.582078,99.573745,49.508108,55.240459,125.815554,121.979001,27.773981,26.356168,31.877730,caminar_adelante,lento
1,0.329137,-0.534679,-0.299742,1.549899,-0.316463,-0.537548,-0.280506,1.014096,0.414566,-0.265260,-0.109191,1.086957,-0.396885,-0.263671,-0.008650,0.615926,0.187398,-0.000030,-0.024351,0.209777,-0.187398,0.000030,0.024351,0.209777,0.205382,0.404334,-0.109187,0.187817,-0.227199,0.402942,-0.120216,0.270454,0.189666,0.798464,0.591631,0.141591,-0.232233,0.804175,0.603969,0.134324,107.432378,99.242670,49.535506,55.440141,123.839759,118.841304,28.887723,28.002809,28.426269,caminar_adelante,lento
2,0.329213,-0.534927,-0.267639,0.963127,-0.315429,-0.537739,-0.248217,0.969157,0.413238,-0.266078,-0.095965,0.399516,-0.397195,-0.264559,0.003380,0.362016,0.187441,0.000238,-0.020340,0.120596,-0.187441,-0.000238,0.020340,0.120596,0.207069,0.404076,-0.102250,0.214312,-0.224851,0.403138,-0.123387,0.118526,0.190355,0.796987,0.597416,0.180303,-0.231740,0.802281,0.602699,0.070008,107.767128,99.193340,49.299399,55.496720,123.830747,117.498486,29.302918,29.197817,25.691395,caminar_adelante,lento
3,0.330488,-0.537180,-0.210959,1.702182,-0.314285,-0.539806,-0.196864,1.542234,0.411700,-0.268739,-0.069036,0.813116,-0.399174,-0.267046,0.025207,0.661699,0.187827,0.000687,-0.009471,0.326569,-0.187827,-0.000687,0.009471,0.326569,0.211055,0.405033,-0.091975,0.331871,-0.220244,0.405955,-0.138259,0.474659,0.192358,0.796461,0.606452,0.278093,-0.231509,0.800816,0.596302,0.196981,107.622708,98.328721,49.331444,56.093805,124.088517,114.572928,29.817158,31.589844,20.755169,caminar_adelante,lento
4,0.330555,-0.537675,-0.162328,1.458987,-0.311485,-0.540247,-0.141048,1.676636,0.407643,-0.271179,-0.055112,0.441213,-0.399184,-0.268683,0.057503,0.970122,0.187043,0.001027,-0.007287,0.070339,-0.187043,-0.001027,0.007287,0.070339,0.215171,0.402986,-0.085293,0.243317,-0.215709,0.404447,-0.137937,0.143696,0.194395,0.792262,0.611466,0.205498,-0.229153,0.795901,0.603304,0.266201,108.051154,98.175832,49.088568,56.422620,125.225634,111.565204,29.947916,34.079828,15.748523,caminar_adelante,lento

In [15]:
features.to_csv("mov_data_proccesed.csv", index=False)